# Generated by Django 3.2 on 2022-06-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel_App', '0004_rename_trip_list_trip_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='Edate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='Sdate',
            field=models.DateField(),
        ),
    ]
