# Generated by Django 3.2 on 2022-06-25 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='comm',
            field=models.ManyToManyField(related_name='course_comm', to='Courses_App.Comment'),
        ),
        migrations.AlterField(
            model_name='course',
            name='des',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_desc', to='Courses_App.desc'),
        ),
    ]
