# Generated by Django 3.2 on 2022-06-24 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='comm',
            field=models.ManyToManyField(related_name='this', to='Courses_App.Comment'),
        ),
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='this', to='Courses_App.desc'),
        ),
    ]
