# Generated by Django 3.2 on 2022-06-25 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses_App', '0002_auto_20220624_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='desc',
        ),
        migrations.AddField(
            model_name='course',
            name='des',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='course_desc', to='Courses_App.desc'),
        ),
        migrations.AlterField(
            model_name='course',
            name='comm',
            field=models.ManyToManyField(related_name='course_comm', to='Courses_App.Comment'),
        ),
    ]
