# Generated by Django 3.2 on 2022-06-22 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Favorite_Books_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='uploaded_by_id',
            new_name='user',
        ),
    ]
