# Generated by Django 3.2 on 2022-06-23 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Favorite_Books_App', '0003_book_users_who_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='users_who_like',
        ),
    ]
